services:

    app.twig.base_twig:
         class: AppBundle\Controller\ContactController

    # ------------------------------------------------------------------------------------------------------------------
    # Authenticators
    # ------------------------------------------------------------------------------------------------------------------

    app.security.token_authenticator:
        class: AppBundle\Service\Security\TokenAuthenticator
        autowire: true

    app.security.admin_login_form_authenticator:
        class: AppBundle\Service\Security\AdminLoginFormAuthenticator
        arguments: ["@form.factory", "@doctrine.orm.entity_manager", "@router", "@security.password_encoder", "@request_stack"]

    app.security.login_form_authenticator:
        class: AppBundle\Service\Security\LoginFormAuthenticator
        arguments: ["@form.factory", "@doctrine.orm.entity_manager", "@router", "@security.password_encoder", "@request_stack"]

    # ------------------------------------------------------------------------------------------------------------------
    # Event Subscribers
    # ------------------------------------------------------------------------------------------------------------------

    app.doctrine.hash_password_subscriber:
        class: AppBundle\EventSubscriber\HashPasswordSubscriber
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    # ------------------------------------------------------------------------------------------------------------------
    # Param converters
    # ------------------------------------------------------------------------------------------------------------------

    app.user_param_converter:
        class: AppBundle\HTTP\ParamConverter\UserParamConverter
        arguments: ['@app.user_manager', '@security.token_storage']
        tags:
            - {name: request.param_converter, converter: app.user_param_converter, priority: 10}

    # ------------------------------------------------------------------------------------------------------------------
    # Services
    # ------------------------------------------------------------------------------------------------------------------

    app.mailer:
        class: AppBundle\Service\Mailer\MailerSender
        arguments: [%mailer_host%, %mailer_user%, %mailer_port%, %mailer_password%]

    app.mailer_service:
        class: AppBundle\Service\Mailer\MailerService
        arguments: ["@app.mailer"]

    app.token_service:
        class: AppBundle\Service\Security\TokenService
        autowire: true

    # ------------------------------------------------------------------------------------------------------------------
    # Pagination
    # ------------------------------------------------------------------------------------------------------------------

    app.pagination_factory:
        class: AppBundle\Service\Pagination\PaginationFactory
        autowire: true

    # ------------------------------------------------------------------------------------------------------------------
    # Admin
    # ------------------------------------------------------------------------------------------------------------------

    admin.property:
        class: AppBundle\Admin\PropertyAdmin
        arguments: [~, AppBundle\Entity\Property, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Մրցույթներ" }
    admin.help:
        class: AppBundle\Admin\HelpfulAdmin
        arguments: [~, AppBundle\Entity\Helpful, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Օգտակար փաստաթղթեր" }

    admin.privacy:
        class: AppBundle\Admin\PrivacyAdmin
        arguments: [~, AppBundle\Entity\Privacy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ընդհանուր պայմաններ" }

    admin.shipment:
        class: AppBundle\Admin\ShipmentAdmin
        arguments: [~, AppBundle\Entity\Shipment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Առաքման տարբերակներ" }

    admin.product.type:
        class: AppBundle\Admin\ProductTypeAdmin
        arguments: [~, AppBundle\Entity\ProductType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Չափման Միավորներ" }

    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Հետադարց Կապ" }

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Նորություններ" }

    admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Նկարներ" }
    admin.property_attribute_condition:
        class: AppBundle\Admin\PropertyCategoryAdmin
        arguments: [~, AppBundle\Entity\PropertyCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ծառայության տեսակը" }

    admin.property_type:
        class: AppBundle\Admin\PropertyTypeAdmin
        arguments: [~, AppBundle\Entity\PropertyType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Մրցույթի տեսակներ" }

    # ------------------------------------------------------------------------------------------------------------------
    # Entity managers
    # ------------------------------------------------------------------------------------------------------------------

    app.help.manager:
        class: AppBundle\Service\Manager\HelpManager
        arguments: ["@app.orm.help.repository", "@app.orm.help.manager"]

    app.privacy.manager:
        class: AppBundle\Service\Manager\PrivacyManager
        arguments: ["@app.orm.privacy.repository", "@app.orm.privacy.manager"]

    app.shipment.manager:
        class: AppBundle\Service\Manager\ShipmentManager
        arguments: ["@app.orm.shipment.repository", "@app.orm.shipment.manager"]

    app.price.manager:
        class: AppBundle\Service\Manager\PriceManager
        arguments: ["@app.orm.price.type.repository", "@app.orm.price.type.manager"]

    app.price_product.manager:
        class: AppBundle\Service\Manager\PriceProductManager
        arguments: ["@app.orm.price_product.type.repository", "@app.orm.price_product.type.manager"]

    app.product.type.manager:
        class: AppBundle\Service\Manager\ProductTypeManager
        arguments: ["@app.orm.product.type.repository", "@app.orm.product.type.manager"]

    app.property.type_manager:
        class: AppBundle\Service\Manager\PropertyTypeManager
        arguments: ["@app.orm.property.type.repository", "@app.orm.property.type.manager"]

    app.news_manager:
        class: AppBundle\Service\Manager\NewsManager
        arguments: ["@app.orm.news.repository", "@app.orm.news.manager"]

    app.image_manager:
        class: AppBundle\Service\Manager\ImageManager
        arguments: ["@app.orm.image.repository", "@app.orm.image.manager", "%kernel.root_dir%"]

    app.file_manager:
        class: AppBundle\Service\Manager\FileManager
        arguments: ["@app.orm.file.repository", "@app.orm.file.manager", "%kernel.root_dir%"]

    app.property_manager:
        class: AppBundle\Service\Manager\PropertyManager
        arguments: ["@app.orm.property.repository", "@app.orm.property.manager"]

    app.property_product_manager:
        class: AppBundle\Service\Manager\PropertyProductManager
        arguments: ["@app.orm.property.product.repository", "@app.orm.property.category.manager"]

    app.property_category_maneger:
        class: AppBundle\Service\Manager\PropertyCategoryManager
        arguments: ["@app.orm.property.category.repository", "@app.orm.property.category.manager"]

    app.conditions_manager:
        class: AppBundle\Service\Manager\ConditionsManager
        arguments: ["@app.orm.conditions.repository", "@app.orm.conditions.manager"]

    app.user_manager:
        class: AppBundle\Service\Manager\UserManager
        arguments: ["@app.orm.user.repository", "@app.orm.user.manager"]

    app.contact_manager:
        class: AppBundle\Service\Manager\ContactManager
        arguments: ["@app.orm.contact.repository", "@app.orm.contact.manager"]
